upstream remnawave-tg-shop         { server 127.0.0.1:8080; }
upstream remnawave-tg-shop-web-api { server 127.0.0.1:8090; }
upstream remnawave-tg-shop-web-frontend { server 127.0.0.1:3000; }

server {
    listen 443 ssl http2;
    server_name webhook.donbaton.tech;

    ssl_certificate     /etc/letsencrypt/live/webhook.donbaton.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/webhook.donbaton.tech/privkey.pem;

    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;

    location / {
        proxy_pass http://remnawave-tg-shop;
    }
}


server {
    listen 443 ssl http2;
    server_name api.donbaton.tech;

    ssl_certificate     /etc/letsencrypt/live/api.donbaton.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.donbaton.tech/privkey.pem;

    location / {
        proxy_http_version 1.1;
        proxy_pass http://remnawave-tg-shop-web-api;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}

server {
    listen 443 ssl http2;
    server_name lk.donbaton.tech donbaton.tech _;

    ssl_certificate     /etc/letsencrypt/live/lk.donbaton.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lk.donbaton.tech/privkey.pem;

    location / {
        proxy_http_version 1.1;
        proxy_pass http://remnawave-tg-shop-web-frontend;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}