"""add_foreground_card_border_colors

Revision ID: 1bcdf998d07d
Revises: 0009_trial_reset_grants
Create Date: 2026-05-11 01:37:30.774201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcdf998d07d'
down_revision: Union[str, Sequence[str], None] = '0009_trial_reset_grants'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('site_settings', sa.Column('foreground_color', sa.String(length=20), nullable=False, server_default='#2B2B2B'))
    op.add_column('site_settings', sa.Column('card_color', sa.String(length=20), nullable=False, server_default='#FFFFFF'))
    op.add_column('site_settings', sa.Column('border_color', sa.String(length=20), nullable=False, server_default='#DDD8D3'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'border_color')
    op.drop_column('site_settings', 'card_color')
    op.drop_column('site_settings', 'foreground_color')
    # ### end Alembic commands ###
