"""add legal document urls to site_settings

Revision ID: 28b35737fcfa
Revises: 0007_accounts_site_user_id
Create Date: 2026-05-10 02:36:24.334243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b35737fcfa'
down_revision: Union[str, Sequence[str], None] = '0007_accounts_site_user_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('privacy_policy_url', sa.String(length=1000), nullable=True))
    op.add_column('site_settings', sa.Column('terms_of_service_url', sa.String(length=1000), nullable=True))
    op.add_column('site_settings', sa.Column('personal_data_url', sa.String(length=1000), nullable=True))
    op.add_column('site_settings', sa.Column('refund_policy_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'refund_policy_url')
    op.drop_column('site_settings', 'personal_data_url')
    op.drop_column('site_settings', 'terms_of_service_url')
    op.drop_column('site_settings', 'privacy_policy_url')
    # ### end Alembic commands ###
