"""add redirect_url to payments

Revision ID: 349c74b38ed6
Revises: 0006_plans_providers
Create Date: 2026-05-03 03:11:09.476516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '349c74b38ed6'
down_revision: Union[str, Sequence[str], None] = '0006_plans_providers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('redirect_url', sa.Text(), nullable=True))
    op.alter_column('pricing_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'site_settings', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_settings', type_='unique')
    op.alter_column('pricing_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('payments', 'redirect_url')
    # ### end Alembic commands ###
