"""add_is_archived_to_pricing_plans

Revision ID: 77d18bb308d7
Revises: 0011_fix_plan_fk
Create Date: 2026-05-17 23:06:31.216017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d18bb308d7'
down_revision: Union[str, Sequence[str], None] = '0011_fix_plan_fk'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_plans', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_pricing_plans_is_archived'), 'pricing_plans', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_plans_is_archived'), table_name='pricing_plans')
    op.drop_column('pricing_plans', 'is_archived')
    # ### end Alembic commands ###
